version: "3.1"
services:
  db:
    container_name: sqlnode-postgres
    image: postgres:10-alpine
    ports:
      - "5433:5432" 
    environment:
      POSTGRES_DB: sqlnode
      POSTGRES_USER: docker 
      POSTGRES_PASSWORD: docker